import React, { useState } from 'react';
import { ChevronDown, ChevronUp, AlertTriangle } from 'lucide-react';

const FaqPage = () => {
  const faqs = [
    {
      q: "Is this platform a substitute for a licensed attorney?",
      a: "No. LegalAssist does not provide binding legal advice, official court advocacy, or active case representation. It acts solely as an educational, AI-driven informational dashboard to help you organize documents, learn legal terms, and understand basic procedural guidelines."
    },
    {
      q: "How accurate is the AI legal guidance?",
      a: "The guidance is generated by our legal AI models based on the details you submit. While it matches keywords and case profiles with standard statutory frameworks, it is not a exhaustive judicial query and may contain omissions. Always verify procedures and statutes with a professional advocate."
    },
    {
      q: "Who can view my uploaded documents?",
      a: "Your uploaded documents and case descriptions are private. They can only be accessed by you, the system administrators for auditing/analytics, and verified advocate panels who evaluate your case details to write replies."
    },
    {
      q: "Is there a fee for using LegalAssist?",
      a: "Citizens can submit complaints and generate AI legal guides completely free of charge. Optional offline representation or extended consultations negotiated directly with advocates are governed by standard advocate fee limits."
    },
    {
      q: "Can I delete my complaints and files?",
      a: "Yes. You have full profile and case management control. You can request deletion of any submitted case file, which will erase the details and all associated documents from our active uploads folder."
    }
  ];

  const [activeIndex, setActiveIndex] = useState(null);

  const toggleFaq = (idx) => {
    setActiveIndex(activeIndex === idx ? null : idx);
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 space-y-16 animate-fade-in">
      <div className="text-center space-y-4">
        <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white">Frequently Asked Questions</h1>
        <p className="text-lg text-slate-500 dark:text-slate-400">
          Everything you need to know about LegalAssist, guidelines, and privacy limits.
        </p>
      </div>

      {/* Accordion List */}
      <div className="space-y-4">
        {faqs.map((f, idx) => (
          <div key={idx} className="border border-slate-200 dark:border-slate-800 rounded-xl bg-white dark:bg-darkCard overflow-hidden">
            <button
              onClick={() => toggleFaq(idx)}
              className="w-full flex justify-between items-center p-6 text-left font-semibold text-slate-800 dark:text-white hover:bg-slate-50 dark:hover:bg-slate-950/20 transition-colors"
            >
              <span>{f.q}</span>
              {activeIndex === idx ? <ChevronUp className="w-5 h-5 text-slate-500" /> : <ChevronDown className="w-5 h-5 text-slate-500" />}
            </button>
            
            {activeIndex === idx && (
              <div className="p-6 pt-0 border-t border-slate-100 dark:border-slate-800 text-sm text-slate-500 dark:text-slate-400 leading-relaxed bg-slate-50/50 dark:bg-slate-950/10">
                {f.a}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Warning Box */}
      <div className="p-6 bg-amber-50 dark:bg-amber-950/20 border border-amber-500/20 rounded-2xl flex items-start gap-4">
        <AlertTriangle className="w-6 h-6 text-amber-500 flex-shrink-0 mt-0.5" />
        <div className="space-y-1">
          <h4 className="font-bold text-amber-800 dark:text-amber-300 text-sm">Official Legal Disclaimer Reminder</h4>
          <p className="text-xs text-amber-700 dark:text-amber-400 leading-relaxed">
            This platform provides informational guidance only and is not a substitute for professional legal advice or court decisions. The platform does not assume civil or criminal liability for actions taken on the basis of AI-generated legal procedures.
          </p>
        </div>
      </div>
    </div>
  );
};

export default FaqPage;
